routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProyectoController;
use App\Http\Controllers\SubProyectoController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\DepartamentoController;
use App\Http\Controllers\DepProyectoController;
use App\Http\Controllers\ProveedorController;
use App\Http\Controllers\PresupuestoController;
use App\Http\Controllers\PagoController;
use App\Http\Controllers\PuertoController;
use App\Http\Controllers\AuditoriaController;

use Spatie\Permission\Traits\HasRoles;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [ProyectoController::class, 'index'])->middleware(['auth'])->name('index');

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


Route::middleware(['auth'])->group(function () {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::get('proyectos/reporte/ver', [ProyectoController::class, 'reporteVer'])->name('proyectos.reporte.ver');
    Route::get('proyectos/reporte/descargar', [ProyectoController::class, 'reporteDescargar'])->name('proyectos.reporte.descargar');
    Route::resource('proyectos', ProyectoController::class);
    Route::resource('departamentos', DepartamentoController::class);
    Route::resource('proveedores', ProveedorController::class);
    Route::resource('puertos', PuertoController::class);
    Route::resource('proyecto.sub_proyectos', SubProyectoController::class);
    Route::resource('departamento.proyectos', DepProyectoController::class);
    Route::resource('sub_proyecto.presupuestos', PresupuestoController::class);
    Route::resource('presupuesto.pagos', PagoController::class);
    Route::get('presupuesto/{presupuesto}/pagos/{pago}/download', [PagoController::class, 'download'])->name('presupuesto.pagos.download');
    Route::get('auditorias', [AuditoriaController::class, 'index'])->name('auditorias');
});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        @yield('title')
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <style>
        .bg-navbar{
            background-color: #292961;
        }
        .bg-sidebar{
            background-color: #F0F0F0;
        }
        .letra-sidebar{
            color: #303030;
        }
        a{
            text-decoration: none;
            color: #212529;
        }
        hr {
            margin-top: 1rem;
            margin-bottom: 1rem;
            border: 0;
            border-top: 1px solid rgba(0, 0, 0, 0.1);
        }
    </style>
    @yield('styles')
</head>
<body>
    @include('sidebar-menu')
    <nav class="navbar navbar-dark bg-navbar">
        <div class="container-fluid">
            <div class="justify-content-start">
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" role="button" aria-controls="offcanvasWithBothOptions">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="dropdown d-flex" style="margin-right: 2.5rem">
                <a href="#" class="d-flex align-items-center link-light text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
                {{-- <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2"> --}}
                <strong>{{ Auth::user()->name }}</strong>
                {{-- <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2"> --}}
                </a>
                {{-- <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2" style="margin-left: 0.5rem"> --}}
                <img src="{{ asset('logo/avatar-profile.svg') }}" alt="" width="32" height="32" class="rounded-circle me-2" style="margin-left: 0.5rem">
                <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2" style="">
                    {{-- <li><a class="dropdown-item" href="#">New project...</a></li> --}}
                    <li><a class="dropdown-item" href="{{ route('users.show', Auth::user()->id) }}">Perfil</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li>
                        {{-- <a class="dropdown-item" href="">Sign out</a> --}}
                        <!-- Authentication -->
                        {{-- <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-responsive-nav-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                <li class="dropdown-item">{{ ('Salir') }}</li>
                            </x-responsive-nav-link>
                        </form> --}}
                        <form action="{{ route('logout') }}" method="POST">
                            @csrf
                            
                            <button type="submit" title="delete" class="dropdown-item" style="border: none; background-color:transparent;">
                                Salir
                            </button>
                        </form>
                    </li>
                </ul>
                {{-- <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2"> --}}
            </div>
        </div>
    </nav>
    <div class="container">
        @yield('content')
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
        integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous">
    </script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous">
    </script>
    @yield('scripts')
</body>
</html>

resources/views/auditorias.blade.php
@extends('app')
@section('styles')
    <style>
        .card-container{
            background-color: #fff;
            /* width: 100%; */

        }
        .titulo{
            margin-top: 3.5rem; 
            margin-bottom: 1.5rem; 
        }
    </style>
@endsection
@section('content')

  <div class="titulo row">
    <div class="mt-7 col-12 mb-2">
        <div class="text-center">
            <h3>Auditoria</h3>
        </div>
    </div>
  </div>

  @if ($message = Session::get('success'))
    <div class="alert alert-success">
        {{ $message }}
    </div>
  @endif

  <div class="shadow p-3 mb-5 bg-white rounded card-container">
    <table class="table">
        <thead>
            <tr class="text-center">
                <th scope="col">Usuario</th>
                <th scope="col">Tabla</th>
                <th scope="col">Id</th>
                <th scope="col">Accion</th>
                <th scope="col">Fecha</th>
              </tr>
        </thead>
        <tbody>
            @foreach ($auditorias as $auditoria)
                <tr class="text-center">
                    <td>{{ $auditoria->user->name }}</td>
                    <td>{{ $auditoria->table }}</td>
                    <td>{{ $auditoria->model_id }}</td>
                    <td>{{ $auditoria->action }}</td>
                    <td>{{ $auditoria->created_at }}</td>
                    <td>
                    </td>
                </tr>
            @endforeach
            </tbody>
      </table>
  </div>


@endsection

resources/views/base.blade.php
<script>
$(document).ready(function(){

var Tripagent_feeReceived = 0 ;
var Tripagent_fee = 0 ;

 if (TripRatepercentage!="0")
 {
   Tripagent_fee = Trippublish_price-(Trippublish_price*(
TripRatepercentage/100));
   Tripagent_feeReceived= Trippublish_price*(TripRatepercentage/100);
  }

$("#agent_fee").val(Tripagent_fee);
$("#agent_fee_received").val(Tripagent_feeReceived);
 })
 </script>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/sidebar-menu.blade.php
<div class="offcanvas offcanvas-start w-25 bg-sidebar" tabindex="-1" id="offcanvas" data-bs-keyboard="false" data-bs-scroll="true" data-bs-backdrop="true">
    <div class="offcanvas-header row pb-0">
        {{-- <div class="row"> --}}
            <div class="col-10">
                <img src="{{ asset('logo/gestapp_logo1.png') }}" alt="" width="100" height="72" class="d-inline-block align-text-top float-start">
            </div>
            <div class="col-2">
                <button type="button" class="btn-close text-reset pt-0" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="col-12 pt-2">
                <h6 class="offcanvas-title d-none d-sm-block" id="offcanvas">Menu</h6>
            </div>
        {{-- </div> --}}
        {{-- <img src="{{ asset('logo/gestapp_logo1.png') }}" alt="" width="60" height="48" class="d-inline-block align-text-top">
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        <h6 class="offcanvas-title d-none d-sm-block" id="offcanvas">Menu</h6> --}}
    </div>
    <div class="offcanvas-body px-0">
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-start" id="menu">
            @if (Auth::user()->hasRole('Admin'))
                <li class="nav-item">
                    <a href="{{ route('proyectos.index') }}" class="nav-link text-truncate letra-sidebar">
                        <i class="fs-5 bi-house"></i><span class="ms-1 d-none d-sm-inline">Home</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('proyectos.index') }}" class="nav-link text-truncate letra-sidebar">
                        <i class="fs-5 bi-table"></i><span class="ms-1 d-none d-sm-inline">Proyectos</span></a>
                </li>
                <li>
                    <a href="{{ route('users.index') }}" class="nav-link text-truncate letra-sidebar">
                        <i class="fs-5 bi-people"></i><span class="ms-1 d-none d-sm-inline">Usuarios</span> </a>
                </li>
                <li>
                    <a href="{{ route('roles.index') }}" class="nav-link text-truncate letra-sidebar">
                          <i class="fs-5 bi bi-person-check"></i><span class="ms-1 d-none d-sm-inline">Roles</span></a>
                </li>
                <li>
                    <a href="{{ route('departamentos.index') }}" class="nav-link text-truncate letra-sidebar">
                        <i class="fs-5 bi-grid"></i><span class="ms-1 d-none d-sm-inline">Departamentos</span></a>
                </li>
                <li>
                    <a href="{{ route('proveedores.index') }}" class="nav-link text-truncate letra-sidebar">
                        <i class="fs-5 bi bi-briefcase"></i><span class="ms-1 d-none d-sm-inline">Proveedores</span></a>
                </li>
                <li>
                    <a href="{{ route('puertos.index') }}" class="nav-link text-truncate letra-sidebar">
                        <img src="{{ asset('logo/anchor-icon.png') }}" alt="" width="17" height="17"><span class="ms-1 d-none d-sm-inline">Puertos</span></a>
                </li>
                <li>
                    <a href="{{ route('auditorias') }}" class="nav-link text-truncate letra-sidebar">
                        <i class="fs-5 bi-table"></i><span class="ms-1 d-none d-sm-inline">Auditoria</span></a>
                </li>
            @elseif (Auth::user()->hasRole('Funcionario'))
                @if(Auth::user()->departamento)
                    <li class="nav-item">
                        <a href="{{ route('departamento.proyectos.index', [Auth::user()->departamento]) }}" class="nav-link text-truncate letra-sidebar">
                            <i class="fs-5 bi-house"></i><span class="ms-1 d-none d-sm-inline">Home</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('departamentos.show', Auth::user()->departamento->id) }}" class="nav-link text-truncate letra-sidebar">
                            <i class="fs-5 bi-grid"></i><span class="ms-1 d-none d-sm-inline"> Departamento de {{ Auth::user()->departamento->nombre }}</span></a>
                    </li>
                @endif
            @endif
            {{-- <li class="dropdown">
                <a href="#" class="nav-link dropdown-toggle  text-truncate letra-sidebar" id="dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fs-5 bi-bootstrap"></i><span class="ms-1 d-none d-sm-inline">Bootstrap</span>
                </a>
                <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdown">
                    <li><a class="dropdown-item" href="#">New project...</a></li>
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item letra-sidebar" href="#">Sign out</a></li>
                </ul>
            </li> --}}
            {{-- <li>
                <a href="#" class="nav-link text-truncate letra-sidebar">
                    <i class="fs-5 bi-speedometer2"></i><span class="ms-1 d-none d-sm-inline">Dashboard</span> </a>
            </li> --}}
        </ul>
    </div>
</div>

resources/views/sin_departamento.blade.php
@extends('app')
@section('styles')
    <style>
        .card-container{
            background-color: #fff;
            /* width: 100%; */

        }
        .titulo{
            margin-top: 3.5rem; 
            margin-bottom: 1.5rem; 
        }
    </style>
@endsection
@section('content')
    <div class="titulo row shadow">
        <div class="mt-7 col-12">
            <div class="d-flex text-center justify-content-center my-3">
                <h2>Oops! No te asignaron a un departamento aún.</h2>
            </div>
            <br>
            <div class="d-flex text-center justify-content-center mt-3 mb-5 pd-3">
                <h2>Contacta con el administrador para que te asignen a uno y asi poder usar la plataforma</h2>
            </div>
        </div>
    </div>

@endsection