routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProyectoController;
use App\Http\Controllers\SubProyectoController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\DepartamentoController;
use App\Http\Controllers\DepProyectoController;
use App\Http\Controllers\ProveedorController;
use App\Http\Controllers\PresupuestoController;
use App\Http\Controllers\PagoController;
use App\Http\Controllers\PuertoController;
use App\Http\Controllers\AuditoriaController;

use Spatie\Permission\Traits\HasRoles;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [ProyectoController::class, 'index'])->middleware(['auth'])->name('index');

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


Route::middleware(['auth'])->group(function () {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::get('proyectos/reporte/ver', [ProyectoController::class, 'reporteVer'])->name('proyectos.reporte.ver');
    Route::get('proyectos/reporte/descargar', [ProyectoController::class, 'reporteDescargar'])->name('proyectos.reporte.descargar');
    Route::resource('proyectos', ProyectoController::class);
    Route::resource('departamentos', DepartamentoController::class);
    Route::resource('proveedores', ProveedorController::class);
    Route::resource('puertos', PuertoController::class);
    Route::resource('proyecto.sub_proyectos', SubProyectoController::class);
    Route::resource('departamento.proyectos', DepProyectoController::class);
    Route::resource('sub_proyecto.presupuestos', PresupuestoController::class);
    Route::resource('presupuesto.pagos', PagoController::class);
    Route::get('presupuesto/{presupuesto}/pagos/{pago}/download', [PagoController::class, 'download'])->name('presupuesto.pagos.download');
    Route::get('auditorias', [AuditoriaController::class, 'index'])->name('auditorias');
});

require __DIR__.'/auth.php';

app/Models/SubProyecto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use App\Models\Proyecto;
use App\Models\Presupuesto;

class SubProyecto extends Model
{
    use HasFactory;

    protected $fillable = [
        'proyecto_id',
        'nombre',
        'descripcion',
        'costo',
        'cotizacion_dia',
        'monto_usd',
        'contratado',
    ];

    public function proyecto()
    {
        return $this->belongsTo(Proyecto::class);
    }
    public function presupuesto()
    {
        return $this->hasOne(Presupuesto::class, 'subproyecto_id');
    }
}

app/Http/Controllers/SubProyectoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;

use App\Models\SubProyecto;
use App\Models\Proyecto;
use App\Models\User;
use App\Models\Puerto;
use App\Models\Departamento;
use App\Models\Estado;
use App\Models\Auditoria;

class SubProyectoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Proyecto $proyecto)
    {
        $sub_proyectos = SubProyecto::latest()->paginate(5);

        return view('sub_proyectos.index', compact('sub_proyectos'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Proyecto $proyecto)
    {   
        $costo_total = 0;
        foreach($proyecto->sub_proyectos as $sub){ 
            $costo_total += $sub->costo;
            error_log('\n' . $sub->costo);
        }
        $saldo_disponible = $proyecto->costo - $costo_total;
        return view('sub_proyectos.create', compact('proyecto','saldo_disponible'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Proyecto $proyecto, Request $request)
    {
        $request->validate([
            'nombre' => 'bail|required|max:200',
            'descripcion' => 'required|max:255',
            'costo' => 'required|numeric',
            // 'contratado' => 'required|numeric',
        ]);
        $costo_total = 0;
        $valido = 1;
        foreach($proyecto->sub_proyectos as $sub){ 
            $costo_total += $sub->costo;
            error_log('\n' . $sub->costo);
        }
        $saldo_disponible = $proyecto->costo - $costo_total;
        if($request->input('costo') > $saldo_disponible || $request->input('costo') > $proyecto->costo ){
            $valido = 0;
            error_log('Entra aca');
        }
        error_log('\nCosto total:' . $costo_total . '\n');
        error_log('\nCosto ingresado:' . $request->input('costo') . '\n');
        error_log('\nCosto del proyecto:' . $proyecto->costo . '\n');
        error_log('\nValido es:' . $valido . '\n');
        $validator = Validator::make($request->all(),
            [
                'costo' => [
                    'required',
                    'numeric',
                ],
            ]
        );

        if($valido == 0){
            $validator->errors()->add('costo', 'El costo supera el presupuesto permitido');
            return view('sub_proyectos.create', compact('proyecto','saldo_disponible'))
            ->withErrors($validator);
        }

        $dolar = $this->dolar();
        $dolarCompra = $dolar['dolarCompra'];
        $monto_usd = $request->input('costo')/$dolarCompra;

        $sub_proyecto = SubProyecto::create(array_merge($request->all(), ["proyecto_id"=>$proyecto->id, 'contratado'=>0, 'cotizacion_dia'=>$dolarCompra, 'monto_usd'=>$monto_usd]));
        // $proyecto->contratado += $sub_proyecto->costo;

        Auditoria::create(['user_id'=>Auth::user()->id,
        'table'=>'sub_proyectos',
        'model_id'=>$sub_proyecto->id,
        'action'=>'Añadió el sub-proyecto: ' . $sub_proyecto->nombre . ' al proyecto: ' . $sub_proyecto->proyecto->nombre]);

        $finalizado = Estado::firstWhere('nombre','Finalizado');
        $enProceso = Estado::firstWhere('nombre','En Proceso');
        if($sub_proyecto->proyecto->estado_id == $finalizado->id){
            $sub_proyecto->proyecto->estado_id = $enProceso->id;
            $sub_proyecto->proyecto->save();
        }

        return redirect()->route('proyectos.show', $proyecto)
        ->with('success','SubProyecto se ha creado exitosamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Proyecto $proyecto, SubProyecto $subProyecto)
    {
        return view('sub_proyectos.detail', compact('proyecto','subProyecto'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Proyecto $proyecto, SubProyecto $subProyecto)
    {
        $costo_total = 0;
        foreach($proyecto->sub_proyectos as $sub){ 
            $costo_total += $sub->costo;
            error_log('\n' . $sub->costo);
        }
        $saldo_disponible = $proyecto->costo - $costo_total;
        return view('sub_proyectos.edit', compact('subProyecto', 'proyecto','saldo_disponible'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Proyecto $proyecto, SubProyecto $sub_proyecto)
    {
        $input = $request->validate([
            'nombre' => 'max:200',
            'descripcion' => 'max:255',
            'costo' => 'numeric',
            // 'contratado' => 'required|numeric',
        ]);

        $dolar = $this->dolar();
        $dolarCompra = $dolar['dolarCompra'];
        $monto_usd = $request->input('costo')/$dolarCompra;

        $sub_proyecto->fill(array_merge($input, ['cotizacion_dia'=>$dolarCompra, 'monto_usd'=>$monto_usd]))->save();

        Auditoria::create(['user_id'=>Auth::user()->id,
        'table'=>'sub_proyectos',
        'model_id'=>$sub_proyecto->id,
        'action'=>'Editó el sub-proyecto: ' . $sub_proyecto->nombre . ' del proyecto: ' . $sub_proyecto->proyecto->nombre]);

        return redirect()->route('proyectos.show',[$proyecto])
        ->with('success','SubProyecto se ha actualizado exitosamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Proyecto $proyecto, SubProyecto $subProyecto)
    {
        $nombre = $subProyecto->nombre;
        $subProyecto->delete();

        Auditoria::create(['user_id'=>Auth::user()->id,
        'table'=>'sub_proyectos',
        'model_id'=>$sub_proyecto->id,
        'action'=>'Eliminó el sub-proyecto: ' . $nombre . ' del proyecto: ' . $proyecto->nombre]);

        return redirect()->route('proyectos.show', $proyecto)
        ->with('success','SubProyecto se ha eliminado exitosamente.');
    }

    public function dolar(){
        $url ="https://dolar.melizeche.com/api/1.0/"; 
 
        $ch = \curl_init($url);

        // Configuring curl options 
        $options = array( 
            CURLOPT_RETURNTRANSFER => true,     
            CURLOPT_HTTPHEADER => array('Accept: application/json'), 
            CURLOPT_SSL_VERIFYPEER => false,     
        ); 
        // Setting curl options 
        \curl_setopt_array( $ch, $options );
        
        // Getting results 
        $response = curl_exec($ch); // Getting jSON result string   
        
        // Cerrar el recurso cURL y liberar recursos del sistema 
        \curl_close($ch);
        //print_r($response);
        
        $data = json_decode($response, true);     
        //var_dump($data);
        $fecha=$data['updated'];
        $date = strtotime($fecha);

        $MydcambiosCompra=$data['dolarpy']['mydcambios']['compra'];
        $MydcambiosVenta=$data['dolarpy']['mydcambios']['venta'];

        $resultado = array('dolarCompra'=>$MydcambiosCompra, 'dolarVenta'=> $MydcambiosVenta);
        return $resultado;
    }
}

resources/views/sub_proyectos/create.blade.php
@extends('app')
@extends('base')
@section('styles')
    <style>
        .card-container{
            background-color: #fff;
            /* width: 100%; */

        }
        .titulo{
            margin-top: 1.5rem; 
            margin-bottom: 1.5rem; 
        }
    </style>
@endsection

@section('content')
    <div class="row d-flex justify-content-center">
        <div class="col-8">
            <div class="row card shadow p-3 m-3 mt-5">
                <div class="titulo col-lg-12 margin-tb">
                    <div class="float-start">
                        <h2>Añadir un nuevo SubProyecto</h2>
                    </div>
                    <div class="float-end">
                        <a class="btn btn-primary" href="{{ route('proyectos.show', [$proyecto]) }}" title="Go back"> <i class="fas fa-backward "></i> </a>
                    </div>
                </div>
            {{-- </div> --}}
            {{-- <div class="row"> --}}
                <div class="col-lg-12 margin-tb">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> Hubieron algunos problemas.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('proyecto.sub_proyectos.store', $proyecto->id) }}" method="POST" >
                        @csrf
                
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Nombre:</strong>
                                    <input type="text" name="nombre" class="form-control" placeholder="Name">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Descripcion:</strong>
                                    <textarea class="form-control" style="height:50px" name="descripcion"
                                        placeholder="Introduction"></textarea>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Costo:</strong>
                                    <input class="form-control" type="number" id="costo" name="costo">
                                    <small>Saldo disponible es: {{ number_format($saldo_disponible, 0, ',', '.') }} </small>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center mt-3">
                                <button type="submit" class="btn btn-primary">Enviar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    
@endsection

resources/views/sub_proyectos/detail.blade.php
@extends('app')
@section('styles')
    <style>
        .card-container{
            background-color: #fff;
            /* width: 100%; */

        }
        .titulo{
            margin-top: 3.5rem; 
            margin-bottom: 1.5rem; 
        }
        a {
            color: #212529
        }
    </style>
@endsection
@section('content')
    <div class="card mb-3 mt-4 shadow">
        <div class="card-header">
            <h1 class="card-title text-center">{{ $subProyecto->nombre }}</h1>
        </div>
        <div class="card-body">
            <div class="row pl-3 pr-3">
                <div class="col-sm-6 mt-2">
                    <a href=" {{ route('proyectos.show', [$proyecto]) }} ">
                        <div class="card shadow">
                            <p class="text-center mt-2 mb-2"><strong>Proyecto: </strong>{{ $proyecto->nombre }}</p>
                        </div>
                    </a>
                </div>
                <div class="col-sm-6 mt-2">
                    <div class="card shadow">
                        <p class="text-center mt-2 mb-2"><strong>Fecha de creación: </strong>{{ date_format($subProyecto->created_at, 'd/m/Y') }}</p>
                    </div>
                </div>
                <div class="col-sm-6 mt-2">
                    <div class="card shadow">
                        <p class="text-center mt-2 mb-2"><strong>Costo: </strong>{{ number_format($subProyecto->costo, 0, ',', '.') }}  PYG</p>
                    </div>
                </div>
                <div class="col-sm-6 mt-2">
                    <div class="card shadow">
                        <p class="text-center mt-2 mb-2"><strong>Contratado: </strong>{{ number_format($subProyecto->contratado, 0, ',', '.') }} PYG</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="card shadow mt-2">
                        <p class="text-center mt-2 mb-2"><strong>Descripción: </strong>{{ $subProyecto->descripcion }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="titulo row">
        <div class="mt-7 col-12">
            <div class="d-flex justify-content-center">
                {{-- @if ($subProyecto->presupuesto && $subProyecto->presupuesto->pago)
                    <div class="justify-content-center">
                        <a class="btn btn-info" href="{{ route('presupuesto.pagos.show', [$subProyecto->presupuesto->id, $subProyecto->presupuesto->pago->id]) }}">
                            Ver Pago 
                        </a>
                    </div> --}}
                @if ($subProyecto->presupuesto)
                    @if ($subProyecto->contratado < $subProyecto->presupuesto->monto )
                        <div class="justify-content-center">
                            <a class="btn btn-primary" href="{{ route('presupuesto.pagos.create', [$subProyecto->presupuesto->id]) }}">
                                Adjuntar Pago 
                            </a>
                        </div>
                    @endif
                @else
                    <div class="justify-content-center">
                        <a class="btn btn-primary" href="{{ route('sub_proyecto.presupuestos.create', [$subProyecto]) }}">
                            Agregar Presupuesto
                        </a>
                    </div>
                @endif
            </div>
        </div>
    </div>

    @if ($subProyecto->presupuesto)
        <div class="titulo row">
            <div class="mt-7 col-12">
                <div class="float-start">
                    <h3>Presupuesto de {{ $subProyecto->nombre }}</h3>
                </div>
            </div>
        </div>

        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                {{ $message }}
            </div>
        @endif

        <div class="shadow p-3 mb-5 bg-white rounded card-container table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th scope="col">Concepto</th>
                    <th scope="col">Proveedor</th>
                    <th scope="col">Monto</th>
                    <th scope="col">Cotizacion del dia</th>
                    <th scope="col">Monto USD</th>
                    <th scope="col">Fecha Creación</th>
                    <th style="width: 10%">Actions</th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        {{-- <td>{{ $subProyecto->presupuesto }}</td> --}}
                        <td>{{ $subProyecto->presupuesto->concepto }}</td>
                        <td>{{ $subProyecto->presupuesto->proveedor->nombre_fantasia }}</td>
                        <td style="text-align:right">{{ number_format($subProyecto->presupuesto->monto, 0, ',', '.') }}</td>
                        <td style="text-align:right">{{ number_format($subProyecto->presupuesto->cotizacion_dia, 2, ',' , '.') }}</td>
                        <td style="text-align:right">{{ number_format($subProyecto->presupuesto->monto_usd, 2, ',', '.') }}</td>
                        <td>{{ date_format($subProyecto->created_at, 'd/m/Y') }}</td>
                        <td style="width: 10%">
                            <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                                <a href="{{ route('sub_proyecto.presupuestos.edit', [$subProyecto, $subProyecto->presupuesto]) }}" class="btn btn-outline-primary btn-sm">Ver</a>
                                <a href="{{ route('sub_proyecto.presupuestos.edit', [$subProyecto, $subProyecto->presupuesto]) }}" class="btn btn-outline-primary btn-sm">Editar</a>
                                <form action="{{ route('sub_proyecto.presupuestos.destroy', [$subProyecto, $subProyecto->presupuesto]) }}" method="POST" style="display: inline-block">
                                    @csrf
                                    @method('DELETE')
                                    
                                    <button type="submit" title="delete" class="btn btn-outline-danger btn-sm">
                                        Eliminar
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    @endif
    
    @if ($subProyecto->presupuesto)
        @if ($subProyecto->presupuesto->pagos->count() > 0)
            <div class="titulo row">
                <div class="mt-7 col-12">
                    <div class="float-start">
                        <h3>Pagos de  {{ $subProyecto->nombre }}</h3>
                    </div>
                </div>
            </div>

            <div class="shadow p-3 mb-5 bg-white rounded card-container table-responsive">
                <table class="table table-striped table-sm">
                    <thead>
                    <tr>
                        <th scope="col">Concepto</th>
                        <th scope="col">Comprobante</th>
                        <th scope="col">Monto</th>
                        <th scope="col">Fecha de Pago</th>
                        <th scope="col">Cotizacion del dia</th>
                        <th scope="col">Monto USD</th>
                        <th scope="col">Monto IVA</th>
                        <th style="width: 10%">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach ($subProyecto->presupuesto->pagos as $pago)
                            <tr>
                                <td>{{ $pago->concepto }}</td>
                                <td>{{ $pago->file }}</td>
                                <td style="text-align:right">{{ number_format($pago->monto, 0, ',', '.') }}</td>
                                <td>{{ date_format($pago->created_at, 'd/m/Y') }}</td>
                                <td style="text-align:right">{{ number_format($pago->cotizacion_dia, 2, ',', '.') }}</td>
                                <td style="text-align:right">{{ number_format($pago->monto_usd, 2, ',', '.') }}</td>
                                <td style="text-align:right">{{ number_format($pago->monto_iva, 0, ',', '.') }}</td>
                                <td style="width: 10%">
                                    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                                        <a href="{{ route('presupuesto.pagos.show', [$subProyecto->presupuesto, $pago]) }}" class="btn btn-outline-primary btn-sm">Ver</a>
                                        @if (Auth::user()->hasRole('Admin'))
                                            <a href="{{ route('presupuesto.pagos.edit', [$subProyecto->presupuesto, $pago]) }}" class="btn btn-outline-primary btn-sm">Editar</a>
                                            <form action="{{ route('presupuesto.pagos.destroy', [$subProyecto->presupuesto, $pago]) }}" method="POST" style="display: inline-block">
                                                @csrf
                                                @method('DELETE')
                                                
                                                <button type="submit" title="delete" class="btn btn-outline-danger btn-sm">
                                                    Eliminar
                                                </button>
                                            </form>
                                        @endif
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        @endif
    @endif
@endsection
@section('scripts')
<script>
    montos_elemeentos = document.getElementsByClassName('monto');
    montos_elemeentos.forEach(element => {
        monto_string = element.innerHTML
        let monto = parseFloat(elementContent);
        element.innerHTML = new Intl.NumberFormat('es-PY').format(monto);
    });
</script>
@endsection

resources/views/sub_proyectos/index.blade.php
@extends('app')
@section('styles')
    <style>
        .card-container{
            background-color: #fff;
            /* width: 100%; */

        }
        .titulo{
            margin-top: 3.5rem; 
            margin-bottom: 1.5rem; 
        }
    </style>
@endsection
@section('content')
    <div class="titulo row">
        <div class="mt-7 col-12">
            <div class="float-start">
                <h2>SubProyectos de </h2>
            </div>
            <div class="float-end">
                <a class="btn btn-primary" href="{{ route('proyectos.create') }}">
                    Añadir SubProyecto
                </a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            {{ $message }}
        </div>
    @endif

    <div class="shadow p-3 mb-5 bg-white rounded card-container table-responsive">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Costo</th>
                <th scope="col">Contratado</th>
                <th style="width: 10%">Actions</th>
              </tr>
            </thead>
            <tbody>
                @foreach ($proyectos as $proyecto)
                <tr>
                    <th scope="row">{{ $i++ }}</th>
                    <td>{{ $proyecto->nombre }}</td>
                    <td>{{ $proyecto->direccion }}</td>
                    <td>{{ $proyecto->user->name }}</td>
                    <td>{{ $proyecto->estado }}</td>
                    <td style="text-align:right">{{ number_format($proyecto->costo, 0, ',', '.') }}</td>
                    <td style="text-align:right">{{ number_format($proyecto->contratado , 0, ',', '.') }}</td>
                    {{-- <td>{{ date_format($proyecto->created_at, 'jS M Y') }}</td> --}}
                    <td style="width: 10%">
                        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                            <a href="{{ route('proyectos.show', $proyecto->id) }}" class="btn btn-info">Ver</a>
                            <button href="{{ route('proyectos.edit', $proyecto->id) }}" class="btn btn-primary">Editar</button>
                            <form action="{{ route('proyectos.destroy', $proyecto->id) }}" method="POST" style="display: inline-block">
                                @csrf
                                @method('DELETE')
                                
                                <button type="submit" title="delete" class="btn btn-danger">
                                    Eliminar
                                </button>
                            </form>
                            {{-- <button type="button" class="btn btn-danger">Eliminar</button> --}}
                          </div>
                        {{-- <a href="{{ route('proyectos.show', $proyecto->id) }}">
                            <i class="fas fa-eye text-success  fa-lg"></i>
                        </a>
                        <a href="{{ route('proyectos.edit', $proyecto->id) }}">
                            <i class="fas fa-edit  fa-lg"></i>
                        </a> --}}
                        {{-- <form action="{{ route('proyectos.destroy', $proyecto->id) }}" method="POST" style="display: inline-block">
                            @csrf
                            @method('DELETE')
                            
                            <button type="submit" title="delete" style="border: none; background-color:transparent;">
                                <i class="fas fa-trash fa-lg text-danger"></i>
                            </button>
                        </form> --}}
                    </td>
                </tr>
                @endforeach
            </tbody>
          </table>
    </div>

@endsection