routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProyectoController;
use App\Http\Controllers\SubProyectoController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\DepartamentoController;
use App\Http\Controllers\DepProyectoController;
use App\Http\Controllers\ProveedorController;
use App\Http\Controllers\PresupuestoController;
use App\Http\Controllers\PagoController;
use App\Http\Controllers\PuertoController;
use App\Http\Controllers\AuditoriaController;

use Spatie\Permission\Traits\HasRoles;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [ProyectoController::class, 'index'])->middleware(['auth'])->name('index');

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


Route::middleware(['auth'])->group(function () {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::get('proyectos/reporte/ver', [ProyectoController::class, 'reporteVer'])->name('proyectos.reporte.ver');
    Route::get('proyectos/reporte/descargar', [ProyectoController::class, 'reporteDescargar'])->name('proyectos.reporte.descargar');
    Route::resource('proyectos', ProyectoController::class);
    Route::resource('departamentos', DepartamentoController::class);
    Route::resource('proveedores', ProveedorController::class);
    Route::resource('puertos', PuertoController::class);
    Route::resource('proyecto.sub_proyectos', SubProyectoController::class);
    Route::resource('departamento.proyectos', DepProyectoController::class);
    Route::resource('sub_proyecto.presupuestos', PresupuestoController::class);
    Route::resource('presupuesto.pagos', PagoController::class);
    Route::get('presupuesto/{presupuesto}/pagos/{pago}/download', [PagoController::class, 'download'])->name('presupuesto.pagos.download');
    Route::get('auditorias', [AuditoriaController::class, 'index'])->name('auditorias');
});

require __DIR__.'/auth.php';

app/Models/Puerto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Puerto extends Model
{
    use HasFactory;

    protected $fillable = [
        'nombre',
        'direccion',
    ];
}

app/Http/Controllers/PuertoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Puerto;
use Illuminate\Http\Request;

class PuertoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $puertos = Puerto::orderBy('id','ASC')->paginate(10);
        return view('puertos.index',compact('puertos'))
            ->with('i', ($request->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('puertos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nombre' => 'required|max:100',
            'direccion' => 'required|max:255',
        ]);

        Puerto::create($request->all());

        return redirect()->route('puertos.index')
                        ->with('success','Puerto creado exitosamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Puerto  $puerto
     * @return \Illuminate\Http\Response
     */
    public function show(Puerto $puerto)
    {
        return view('puertos.show', compact('puerto'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Puerto  $puerto
     * @return \Illuminate\Http\Response
     */
    public function edit(Puerto $puerto)
    {
        return view('puertos.edit', compact('puerto'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Puerto  $puerto
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Puerto $puerto)
    {
        $input = $this->validate($request, [
            'nombre' => 'max:100',
            'direccion' => 'max:255',
        ]);

        $puerto->fill($input)->save();

        return redirect()->route('puertos.index')
                        ->with('success','Puerto se ha actualizado exitosamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Puerto  $puerto
     * @return \Illuminate\Http\Response
     */
    public function destroy(Puerto $puerto)
    {
        $puerto->delete();
        return redirect()->route('puertos.index')
        ->with('success','Proveedor ha sido eliminado exitosamente.');
    }
}

resources/views/puertos/create.blade.php
@extends('app')

@section('styles')
    <style>
        .card-container{
            background-color: #fff;
            /* width: 100%; */

        }
        .titulo{
            margin-top: 1.5rem; 
            margin-bottom: 1.5rem; 
        }
    </style>
@endsection

@section('content')
    <div class="row d-flex justify-content-center">
        <div class="col-8">
            <div class="row card shadow p-3 m-3 mt-5">
                <div class="titulo col-lg-12">
                    <div class="float-start">
                        <h2>Añadir un nuevo Puerto</h2>
                    </div>
                    <div class="float-end">
                        <a class="btn btn-primary" href="{{ route('proveedores.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
                    </div>
                </div>
                <div class="col-lg-12 margin-tb">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> Hubieron algunos problemas.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('puertos.store') }}" method="POST" >
                        @csrf
                
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Nombre:</strong>
                                    <input type="text" name="nombre" class="form-control" placeholder="Nombre">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 mt-3">
                                <div class="form-group">
                                    <strong>Direccion:</strong>
                                    <input type="text" name="direccion" class="form-control" placeholder="Direccion del Puerto">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center mt-3">
                                <button type="submit" class="btn btn-primary">Enviar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/puertos/detail.blade.php
@extends('app')
@section('styles')
    <style>
        .card-container{
            background-color: #fff;
            /* width: 100%; */

        }
        .titulo{
            margin-top: 3.5rem; 
            margin-bottom: 1.5rem; 
        }
    </style>
@endsection
@section('content')
    <div class="card mb-3 mt-4 shadow">
        <div class="card-header">
            <h1 class="card-title text-center">{{ $proyecto->nombre }}</h1>
        </div>
        <div class="card-body">
            <div class="row pl-3 pr-3">
                <div class="col-4 ml-3">
                    <div class="card shadow">
                        <p class="text-center mt-2 mb-2"><strong>Reponsable: </strong>{{ $proyecto->user->name }}</p>
                    </div>
                </div>
                <div class="col-4 mr-3">
                    <div class="card shadow">
                        <p class="text-center mt-2 mb-2"><strong>Departamento: </strong>{{ $proyecto->departamento->nombre }}</p>
                    </div>
                </div>
                <div class="col-4">
                    <div class="card shadow">
                        <p class="text-center mt-2 mb-2"><strong>Fecha de creación: </strong>{{ date_format($proyecto->created_at, 'd/m/Y') }}</p>
                    </div>
                </div>
                <div class="col-4 mt-2">
                    <div class="card shadow">
                        <p class="text-center mt-2 mb-2"><strong>Estado: </strong>{{ $proyecto->estado->nombre }}</p>
                    </div>
                </div>
                <div class="col-4 mt-2">
                    <div class="card shadow">
                        <p class="text-center mt-2 mb-2"><strong>Costo: </strong>{{ $proyecto->costo }}</p>
                    </div>
                </div>
                <div class="col-4 mt-2">
                    <div class="card shadow">
                        <p class="text-center mt-2 mb-2"><strong>Contratado: </strong>{{ $proyecto->contratado }}</p>
                    </div>
                </div>
                <div class="col-12">
                    {{-- <div class="card shadow"> --}}
                        <p class="text-center mt-2 mb-2">{{ $proyecto->descripcion }}</p>
                    {{-- </div> --}}
                </div>
            </div>
        </div>
    </div>
    <div class="titulo row">
        <div class="mt-7 col-12">
            <div class="float-start">
                <h3>SubProyectos de {{$proyecto->nombre}}</h3>
            </div>
            <div class="float-end">
                <a class="btn btn-primary" href="{{ route('proyecto.sub_proyectos.create', [$proyecto]) }}">
                    Añadir SubProyecto
                </a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            {{ $message }}
        </div>
    @endif

    <div class="shadow p-3 mb-5 bg-white rounded card-container">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Costo</th>
                <th scope="col">Contratado</th>
                <th style="width: 10%">Actions</th>
              </tr>
            </thead>
            <tbody>
                @foreach ($proyecto->sub_proyectos as $sub_proyecto)
                <tr>
                    <th scope="row">{{ $i++ }}</th>
                    <td>{{ $sub_proyecto->nombre }}</td>
                    <td>{{ $sub_proyecto->descripcion }}</td>
                    <td>{{ $sub_proyecto->costo }}</td>
                    <td>{{ $sub_proyecto->contratado }}</td>
                    {{-- <td>{{ date_format($proyecto->created_at, 'jS M Y') }}</td> --}}
                    <td style="width: 10%">
                        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                            <a href="{{ route('proyecto.sub_proyectos.show', [$proyecto, $sub_proyecto]) }}" class="btn btn-outline-primary">Ver</a>
                            <a href="{{ route('proyecto.sub_proyectos.edit', [$proyecto, $sub_proyecto]) }}" class="btn btn-outline-primary">Editar</a>
                            <form action="{{ route('proyecto.sub_proyectos.destroy', [$proyecto, $sub_proyecto]) }}" method="POST" style="display: inline-block">
                                @csrf
                                @method('DELETE')
                                
                                <button type="submit" title="delete" class="btn btn-outline-danger">
                                    Eliminar
                                </button>
                            </form>
                            {{-- <button type="button" class="btn btn-danger">Eliminar</button> --}}
                          </div>
                        {{-- <a href="{{ route('proyectos.show', $proyecto->id) }}">
                            <i class="fas fa-eye text-success  fa-lg"></i>
                        </a>
                        <a href="{{ route('proyectos.edit', $proyecto->id) }}">
                            <i class="fas fa-edit  fa-lg"></i>
                        </a> --}}
                        {{-- <form action="{{ route('proyectos.destroy', $proyecto->id) }}" method="POST" style="display: inline-block">
                            @csrf
                            @method('DELETE')
                            
                            <button type="submit" title="delete" style="border: none; background-color:transparent;">
                                <i class="fas fa-trash fa-lg text-danger"></i>
                            </button>
                        </form> --}}
                    </td>
                </tr>
                @endforeach
            </tbody>
          </table>
    </div>

@endsection

resources/views/puertos/edit.blade.php
@extends('app')

@section('styles')
    <style>
        .card-container{
            background-color: #fff;
            /* width: 100%; */

        }
        .titulo{
            margin-top: 1.5rem; 
            margin-bottom: 1.5rem; 
        }
    </style>
@endsection

@section('content')
    <div class="row d-flex justify-content-center">
        <div class="col-8">
            <div class="row card shadow p-3 m-3 mt-5">
                <div class="titulo col-lg-12 margin-tb">
                    <div class="float-start">
                        <h2>Editar Puerto</h2>
                    </div>
                    <div class="float-end">
                        <a class="btn btn-primary" href="{{ route('puertos.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
                    </div>
                </div>
                <div class="col-lg-12 margin-tb">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> Hubieron algunos problemas.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('puertos.update',['puerto' => $puerto]) }}" method="POST" >
                        @csrf
                        @method('PATCH')
                
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Nombre:</strong>
                                    <input type="text" name="nombre" value="{{ $puerto->nombre }}" class="form-control" placeholder="Nombre">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 mt-3">
                                <div class="form-group">
                                    <strong>Direccion:</strong>
                                    <input type="text" name="direccion" value="{{ $puerto->direccion }}" class="form-control" placeholder="Direccion">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center mt-3">
                                <button type="submit" class="btn btn-primary">Enviar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/puertos/index.blade.php
@extends('app')
@section('styles')
    <style>
        .card-container{
            background-color: #fff;
            /* width: 100%; */

        }
        .titulo{
            margin-top: 3.5rem; 
            margin-bottom: 1.5rem; 
        }
    </style>
@endsection
@section('content')
    <div class="titulo row">
        <div class="mt-7 col-12">
            <div class="float-start">
                <h2>Puertos</h2>
            </div>
            @if (Auth::user()->hasRole('Admin'))
                <div class="float-end">
                    <a class="btn btn-primary" href="{{ route('puertos.create') }}">
                        Agregar Puerto
                    </a>
                </div>
            @endif
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            {{ $message }}
        </div>
    @endif

    <div class="shadow p-3 mb-5 bg-white rounded card-container">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Direccion</th>
                <th style="width: 10%">Actions</th>
              </tr>
            </thead>
            <tbody>
                @foreach ($puertos as $puerto)
                <tr>
                    <th scope="row">{{ $i++ }}</th>
                    <td>{{ $puerto->nombre }}</td>
                    <td>{{ $puerto->direccion }}</td>
                    <td style="width: 10%">
                        @if (Auth::user()->hasRole('Admin'))
                            <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                                <a href="{{ route('puertos.edit', [$puerto]) }}" class="btn btn-outline-primary">Ver</a>
                                <a href="{{ route('puertos.edit', [$puerto]) }}" class="btn btn-outline-primary">Editar</a>
                                <form action="{{ route('puertos.destroy', [$puerto]) }}" method="POST" style="display: inline-block">
                                    @csrf
                                    @method('DELETE')
                                    
                                    <button type="submit" title="delete" class="btn btn-outline-danger">
                                        Eliminar
                                    </button>
                                </form>
                            </div>
                          @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
          </table>
    </div>

@endsection