routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProyectoController;
use App\Http\Controllers\SubProyectoController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\DepartamentoController;
use App\Http\Controllers\DepProyectoController;
use App\Http\Controllers\ProveedorController;
use App\Http\Controllers\PresupuestoController;
use App\Http\Controllers\PagoController;
use App\Http\Controllers\PuertoController;
use App\Http\Controllers\AuditoriaController;

use Spatie\Permission\Traits\HasRoles;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [ProyectoController::class, 'index'])->middleware(['auth'])->name('index');

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


Route::middleware(['auth'])->group(function () {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::get('proyectos/reporte/ver', [ProyectoController::class, 'reporteVer'])->name('proyectos.reporte.ver');
    Route::get('proyectos/reporte/descargar', [ProyectoController::class, 'reporteDescargar'])->name('proyectos.reporte.descargar');
    Route::resource('proyectos', ProyectoController::class);
    Route::resource('departamentos', DepartamentoController::class);
    Route::resource('proveedores', ProveedorController::class);
    Route::resource('puertos', PuertoController::class);
    Route::resource('proyecto.sub_proyectos', SubProyectoController::class);
    Route::resource('departamento.proyectos', DepProyectoController::class);
    Route::resource('sub_proyecto.presupuestos', PresupuestoController::class);
    Route::resource('presupuesto.pagos', PagoController::class);
    Route::get('presupuesto/{presupuesto}/pagos/{pago}/download', [PagoController::class, 'download'])->name('presupuesto.pagos.download');
    Route::get('auditorias', [AuditoriaController::class, 'index'])->name('auditorias');
});

require __DIR__.'/auth.php';

app/Http/Controllers/DepProyectoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Proyecto;
use App\Models\Puerto;
use App\Models\Estado;
use App\Models\Departamento;
use Illuminate\Http\Request;

class DepProyectoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, Departamento $departamento)
    {
        // $proyectos = $departamento->proyectos->paginate(5);
        $proyectos = $departamento->proyectos;

        return view('dep_proyectos.index', compact('departamento','proyectos'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Departamento $departamento)
    {
        $users = $departamento->usuarios;
        $puertos = Puerto::all();
        return view('dep_proyectos.create',compact('departamento','users','puertos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Departamento $departamento)
    {
        $request->validate([
            'nombre' => 'required|max:200',
            'descripcion' => 'required|max:255',
            'puerto_id' => 'required|exists:puertos,id',
            'user_id' => 'required|exists:users,id',
            'costo' => 'required|numeric',
            // 'contratado' => 'required|numeric',
        ]);
        $estado = Estado::firstOrCreate([
            'nombre' => 'Pendiente'
        ]);

        $dolar = $this->dolar();
        $dolarCompra = $dolar['dolarCompra'];
        $monto_usd = $request->input('costo')/$dolarCompra;


        Proyecto::create(array_merge($request->all(), ['departamento_id'=>$departamento->id , 'estado_id' => $estado->id, 'contratado'=>0, 'cotizacion_dia'=>$dolarCompra, 'monto_usd'=>$monto_usd]));

        return redirect()->route('departamento.proyectos.index',$departamento)
        ->with('success','Proyecto se ha creado exitosamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Proyecto  $proyecto
     * @return \Illuminate\Http\Response
     */
    public function show(Departamento $departamento, Proyecto $proyecto)
    {
        return view('dep_proyectos.detail', compact('proyecto'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Proyecto  $proyecto
     * @return \Illuminate\Http\Response
     */
    public function edit(Departamento $departamento, Proyecto $proyecto)
    {
        $users = $departamento->usuarios;
        $estados = Estado::all();
        $puertos = Puerto::all();
        return view('dep_proyectos.edit', compact('proyecto','users','estados','puertos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Proyecto  $proyecto
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Departamento $departamento, Proyecto $proyecto)
    {
        $input = $request->validate([
            'nombre' => 'max:200',
            'descripcion' => 'max:200',
            'puerto_id' => 'exists:puertos,id',
            'user_id' => 'exists:users,id',
            'estado_id' => 'exists:estados,id',
            'costo' => 'numeric',
        ]);
        $dolar = $this->dolar();
        $dolarCompra = $dolar['dolarCompra'];
        $monto_usd = $request->input('costo')/$dolarCompra;
        $proyecto->fill(array_merge($input, ['cotizacion_dia'=>$dolarCompra, 'monto_usd'=>$monto_usd]))->save();
        return redirect()->route('departamento.proyectos.index', $departamento)
        ->with('success','Proyecto se ha actualizado exitosamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Proyecto  $proyecto
     * @return \Illuminate\Http\Response
     */
    public function destroy(Departamento $departamento, Proyecto $proyecto)
    {
        $proyecto->delete();
        return redirect()->route('departamento.proyectos.index', $departamento)
        ->with('success','El proyecto ha sido eliminado exitosamente.');
    }

    public function dolar(){
        $url ="https://dolar.melizeche.com/api/1.0/"; 
 
        $ch = \curl_init($url);

        // Configuring curl options 
        $options = array( 
            CURLOPT_RETURNTRANSFER => true,     
            CURLOPT_HTTPHEADER => array('Accept: application/json'), 
            CURLOPT_SSL_VERIFYPEER => false,     
        ); 
        // Setting curl options 
        \curl_setopt_array( $ch, $options );
        
        // Getting results 
        $response = curl_exec($ch); // Getting jSON result string   
        
        // Cerrar el recurso cURL y liberar recursos del sistema 
        \curl_close($ch);
        //print_r($response);
        
        $data = json_decode($response, true);     
        //var_dump($data);
        $fecha=$data['updated'];
        $date = strtotime($fecha);

        $MydcambiosCompra=$data['dolarpy']['mydcambios']['compra'];
        $MydcambiosVenta=$data['dolarpy']['mydcambios']['venta'];

        $resultado = array('dolarCompra'=>$MydcambiosCompra, 'dolarVenta'=> $MydcambiosVenta);
        return $resultado;
    }
}

resources/views/dep_proyectos/create.blade.php
@extends('app')

@section('styles')
    <style>
        .card-container{
            background-color: #fff;
            /* width: 100%; */

        }
        .titulo{
            margin-top: 1.5rem; 
            margin-bottom: 1.5rem; 
        }
    </style>
@endsection

@section('content')
    <div class="row d-flex justify-content-center">
        <div class="col-8">
            <div class="row card shadow p-3 m-3 mt-5">
                <div class="titulo col-lg-12">
                    <div class="float-start">
                        <h2>Añadir un nuevo Proyecto</h2>
                    </div>
                    <div class="float-end">
                        <a class="btn btn-primary" href="{{ route('proyectos.index') }}" title="Atrás"> <i class="fas fa-backward "></i> </a>
                    </div>
                </div>
                <div class="col-lg-12 margin-tb">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> Hubieron algunos problemas.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('departamento.proyectos.store', [$departamento]) }}" method="POST" >
                        @csrf
                
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Nombre:</strong>
                                    <input type="text" name="nombre" class="form-control" placeholder="Name">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Descripción:</strong>
                                    <textarea class="form-control" style="height:50px" name="descripcion"
                                        placeholder="Introduction"></textarea>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Costo:</strong>
                                    <input class="form-control" type="number" id="costo" name="costo">
                                    <small>Obs: Ingresar monto en guaraníes.</small>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group mb-3">
                                    <strong>Seleccionar un responsable:</strong>
                                    <select required name="user_id" class="form-control">
                                        @foreach ($users as $user)
                                            <option value="{{ $user->id }}">{{ $user->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('category')
                                        <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group mb-3">
                                    <strong>Seleccionar un puerto:</strong>
                                    <select required name="puerto_id" class="form-control">
                                        @foreach ($puertos as $puerto)
                                            <option value="{{ $puerto->id }}">{{ $puerto->nombre }}</option>
                                        @endforeach
                                    </select>
                                    @error('puerto')
                                        <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Enviar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dep_proyectos/detail.blade.php
@extends('app')
@section('styles')
    <style>
        .card-container{
            background-color: #fff;
            /* width: 100%; */

        }
        .titulo{
            margin-top: 3.5rem; 
            margin-bottom: 1.5rem; 
        }
    </style>
@endsection
@section('content')
    <div class="card mb-3 mt-4 shadow">
        <div class="card-header">
            <h1 class="card-title text-center">{{ $proyecto->nombre }}</h1>
        </div>
        <div class="card-body">
            <div class="row pl-3 pr-3">
                <div class="col-4 ml-3">
                    <div class="card shadow">
                        <p class="text-center mt-2 mb-2"><strong>Reponsable: </strong>{{ $proyecto->user->name }}</p>
                    </div>
                </div>
                <div class="col-4 mr-3">
                    <div class="card shadow">
                        <p class="text-center mt-2 mb-2"><strong>Departamento: </strong>{{ $proyecto->departamento->nombre }}</p>
                    </div>
                </div>
                <div class="col-4">
                    <div class="card shadow">
                        <p class="text-center mt-2 mb-2"><strong>Fecha de creación: </strong>{{ date_format($proyecto->created_at, 'd/m/Y') }}</p>
                    </div>
                </div>
                <div class="col-4 mt-2">
                    <div class="card shadow">
                        <p class="text-center mt-2 mb-2"><strong>Estado: </strong>{{ $proyecto->estado->nombre }}</p>
                    </div>
                </div>
                <div class="col-4 mt-2">
                    <div class="card shadow">
                        <p class="text-center mt-2 mb-2"><strong>Costo: </strong>{{ $proyecto->costo }} PYG</p>
                    </div>
                </div>
                <div class="col-4 mt-2">
                    <div class="card shadow">
                        <p class="text-center mt-2 mb-2"><strong>Contratado: </strong>{{ $proyecto->contratado }}</p>
                    </div>
                </div>
                <div class="col-12">
                    {{-- <div class="card shadow"> --}}
                        <p class="text-center mt-2 mb-2">{{ $proyecto->descripcion }}</p>
                    {{-- </div> --}}
                </div>
            </div>
        </div>
    </div>
    <div class="titulo row">
        <div class="mt-7 col-12">
            <div class="float-start">
                <h3>SubProyectos de {{$proyecto->nombre}}</h3>
            </div>
            <div class="float-end">
                <a class="btn btn-primary" href="{{ route('proyecto.sub_proyectos.create', [$proyecto]) }}">
                    Añadir SubProyecto
                </a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            {{ $message }}
        </div>
    @endif

    <div class="shadow p-3 mb-5 bg-white rounded card-container">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Costo</th>
                <th scope="col">Cotizacion del dia</th>
                <th scope="col">Monto USD</th>
                <th scope="col">Contratado</th>
                <th style="width: 10%">Actions</th>
              </tr>
            </thead>
            <tbody>
                @foreach ($proyecto->sub_proyectos as $sub_proyecto)
                <tr>
                    <th scope="row">{{ $i++ }}</th>
                    <td>{{ $sub_proyecto->nombre }}</td>
                    <td>{{ $sub_proyecto->descripcion }}</td>
                    <td>{{ number_format($sub_proyecto->costo, 0, ',', '.') }}</td>
                    <td>{{ number_format($sub_proyecto->cotizacion_dia , 2, ',', '.') }}</td>
                    <td>{{ number_format($sub_proyecto->monto_usd, 2, ',', '.') }}</td>
                    <td>{{ number_format($sub_proyecto->contratado , 0, ',', '.') }}</td>
                    {{-- <td>{{ date_format($proyecto->created_at, 'jS M Y') }}</td> --}}
                    <td style="width: 10%">
                        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                            <a href="{{ route('proyecto.sub_proyectos.show', [$proyecto, $sub_proyecto]) }}" class="btn btn-outline-primary">Ver</a>
                            <a href="{{ route('proyecto.sub_proyectos.edit', [$proyecto, $sub_proyecto]) }}" class="btn btn-outline-primary">Editar</a>
                            <form action="{{ route('proyecto.sub_proyectos.destroy', [$proyecto, $sub_proyecto]) }}" method="POST" style="display: inline-block">
                                @csrf
                                @method('DELETE')
                                
                                <button type="submit" title="delete" class="btn btn-outline-danger">
                                    Eliminar
                                </button>
                            </form>
                            {{-- <button type="button" class="btn btn-danger">Eliminar</button> --}}
                          </div>
                        {{-- <a href="{{ route('proyectos.show', $proyecto->id) }}">
                            <i class="fas fa-eye text-success  fa-lg"></i>
                        </a>
                        <a href="{{ route('proyectos.edit', $proyecto->id) }}">
                            <i class="fas fa-edit  fa-lg"></i>
                        </a> --}}
                        {{-- <form action="{{ route('proyectos.destroy', $proyecto->id) }}" method="POST" style="display: inline-block">
                            @csrf
                            @method('DELETE')
                            
                            <button type="submit" title="delete" style="border: none; background-color:transparent;">
                                <i class="fas fa-trash fa-lg text-danger"></i>
                            </button>
                        </form> --}}
                    </td>
                </tr>
                @endforeach
            </tbody>
          </table>
    </div>

@endsection

resources/views/dep_proyectos/edit.blade.php
@extends('app')

@section('styles')
    <style>
        .card-container{
            background-color: #fff;
            /* width: 100%; */

        }
        .titulo{
            margin-top: 1.5rem; 
            margin-bottom: 1.5rem; 
        }
    </style>
@endsection

@section('content')
    <div class="row d-flex justify-content-center">
        <div class="col-8">
            <div class="row card shadow p-3 m-3 mt-5">
                <div class="titulo col-lg-12 margin-tb">
                    <div class="float-start">
                        <h2>Editar Proyecto</h2>
                    </div>
                    <div class="float-end">
                        <a class="btn btn-primary" href="{{ route('proyectos.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
                    </div>
                </div>
                <div class="col-lg-12 margin-tb">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> Hubieron algunos problemas.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('proyectos.update',['proyecto' => $proyecto]) }}" method="POST" >
                        @csrf
                        @method('PATCH')
                
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Nombre:</strong>
                                    <input type="text" name="nombre" class="form-control" value="{{ $proyecto->nombre }}" placeholder="Name">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Descripcion:</strong>
                                    <textarea class="form-control" style="height:50px" name="descripcion"
                                        placeholder="Introduction">{{ $proyecto->descripcion }}</textarea>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Costo:</strong>
                                    <input class="form-control" type="number" id="costo" name="costo" value="{{ $proyecto->costo }}">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group mb-3">
                                    <strong>Estado:</strong>
                                    <select required name="estado_id" class="form-control">
                                        @foreach ($estados as $estado)
                                            <option value="{{ $estado->id }}" {{ $proyecto->estado_id == $estado->id ? "selected" : "" }}>{{ $estado->nombre }}</option>
                                        @endforeach
                                    </select>
                                    @error('category')
                                        <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group mb-3">
                                    <strong>Seleccionar un responsable:</strong>
                                    <select required name="user_id" class="form-control">
                                        @foreach ($users as $user)
                                            <option value="{{ $user->id }}" {{ $proyecto->user_id == $user->id ? "selected" : "" }}>{{ $user->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('category')
                                        <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group mb-3">
                                    <strong>Seleccionar un puerto:</strong>
                                    <select required name="puerto_id" class="form-control">
                                        @foreach ($puertos as $puerto)
                                            <option value="{{ $puerto->id }}" {{ $proyecto->puerto_id == $puerto->id ? "selected" : "" }}>{{ $puerto->nombre }}</option>
                                        @endforeach
                                    </select>
                                    @error('category')
                                        <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Enviar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dep_proyectos/index.blade.php
@extends('app')
@section('styles')
    <style>
        .card-container{
            background-color: #fff;
            /* width: 100%; */

        }
        .titulo{
            margin-top: 3.5rem; 
            margin-bottom: 1.5rem; 
        }
    </style>
@endsection
@section('content')
    <div class="titulo row">
        <div class="mt-7 col-12">
            <div class="float-start">
                <h2>Proyectos del departamento de {{ $departamento->nombre }}</h2>
            </div>
            @if (Auth::user()->hasRole('Admin'))
                <div class="float-end">
                    <a class="btn btn-primary" href="{{ route('departamento.proyectos.create', $departamento) }}">
                        Agregar Proyecto
                    </a>
                </div>
            @endif
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            {{ $message }}
        </div>
    @endif

    <div class="shadow p-3 mb-5 bg-white rounded card-container">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                {{-- <th scope="col">Departamento</th> --}}
                <th scope="col">Puerto</th>
                <th scope="col">Responsable</th>
                <th scope="col">Estado</th>
                <th scope="col">Costo</th>
                <th scope="col">Cotizacion del dia</th>
                <th scope="col">Monto USD</th>
                <th scope="col">Contratado</th>
                <th style="width: 10%">Actions</th>
              </tr>
            </thead>
            <tbody>
                @foreach ($proyectos as $proyecto)
                <tr>
                    <th scope="row">{{ $i++ }}</th>
                    <td>{{ $proyecto->nombre }}</td>
                    {{-- <td>{{ $proyecto->departamento->nombre }}</td> --}}
                    <td>{{ $proyecto->puerto->nombre }}</td>
                    <td>{{ $proyecto->user->name }}</td>
                    <td>{{ $proyecto->estado->nombre }}</td>
                    <td>{{ number_format($proyecto->costo, 0, ',', '.') }}</td>
                    <td>{{ number_format($proyecto->cotizacion_dia, 2, ',', '.') }}</td>
                    <td>{{ number_format($proyecto->monto_usd, 2, ',', '.') }}</td>
                    <td>{{ number_format($proyecto->contratado, 0, ',', '.') }}</td>
                    {{-- <td>{{ date_format($proyecto->created_at, 'jS M Y') }}</td> --}}
                    <td style="width: 10%">
                        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                            <a href="{{ route('departamento.proyectos.show', [$departamento, $proyecto]) }}" class="btn btn-outline-primary">Ver</a>
                            @if (Auth::user()->hasRole('Admin'))
                                <a href="{{ route('departamento.proyectos.edit', [$departamento, $proyecto]) }}" class="btn btn-outline-primary">Editar</a>
                                <form action="{{ route('proyectos.destroy', [$departamento, $proyecto]) }}" method="POST" style="display: inline-block">
                                    @csrf
                                    @method('DELETE')
                                    
                                    <button type="submit" title="delete" class="btn btn-outline-danger">
                                        Eliminar
                                    </button>
                                </form>
                            @endif
                          </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
          </table>
    </div>

    <div class="row d-flex justify-content-center">
        <div class="col-12">
            <!-- Chart's container -->
        <h2 class="text-center">Cantidad de Proyectos por Estado</h2>
        <div id="chart" style="height: 300px;"></div>
            <!-- Charting library -->
            <script src="https://unpkg.com/echarts/dist/echarts.min.js"></script>
            <!-- Chartisan -->
            <script src="https://unpkg.com/@chartisan/echarts/dist/chartisan_echarts.js"></script>
            <!-- Your application script -->
            <script>
                const chart1 = new Chartisan({
                    el: '#chart',
                    url: "@chart('proyectos_dep_chart')"+"?id={{ $departamento->id }}",
                    hooks: new ChartisanHooks()
                    .colors(['#4299E1','#FE0045','#C07EF1','#67C560','#ECC94B'])
                        .datasets('bar')
                        .axis(true)
                });
            </script>
        </div>
    </div>

@endsection